#!/bin/sh -ex

wwan_nic=${1:-eth0}
lan_nic=${2:-eth1}
action=${3:-enable}
net_base=${4:-192.168.1}

#sudo killall dnsmasq ||:

sudo iptables --flush
#sudo iptables --table nat --flush
#sudo iptables --delete-chain
#sudo iptables --table nat --delete-chain
sudo ip a f "$lan_nic"

case "$action" in
enable)
    sudo sysctl -w net.ipv4.ip_forward=1

    sudo ip l s "$lan_nic" up
    sudo ip a a "${net_base}.1/24" dev "$lan_nic" brd + ||:
#    sudo iptables -A INPUT -i $lan_nic -j ACCEPT
#    sudo iptables -A OUTPUT -o $lan_nic -j ACCEPT
#    sudo iptables -A FORWARD -o $lan_nic -j ACCEPT
    sudo iptables -t nat -A POSTROUTING -o "$wwan_nic" -j MASQUERADE
    sudo iptables -t nat -A POSTROUTING -s "${net_base}.0/24" -j MASQUERADE
    #sudo dnsmasq -p 153 -i "$lan_nic" -F "${net_base}.2,${net_base}.127,5m" #--enable-tftp --tftp-root=/tftpboot
    sudo systemctl restart isc-dhcp-server.service
    ;;
disable)
    sudo ip l s "$lan_nic" down
    sudo sysctl -w net.ipv4.ip_forward=1
    ;;
esac
