#!/bin/sh -ex

wwan_nic=${1:-wlp0s20f3}
lan_nic=${2:-enp0s31f6}
action=${3:-enable}
net_base=${4:-192.168.1}


sudo iptables --flush
sudo ip a f "$lan_nic"

case "$action" in
enable)
    sudo ip l s "$lan_nic" up
    sudo ip a a "${net_base}.1/24" dev "$lan_nic" brd + ||:
    #sudo iptables -A FORWARD -o $lan_nic -j ACCEPT
    #sudo iptables -A FORWARD -i "$wwan_nic" -o "$lan_nic" -s "${net_base}.0/24" -m conntrack --ctstate NEW -j ACCEPT
    #sudo iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    #sudo iptables -A POSTROUTING -t nat -j MASQUERADE
    sudo iptables -t nat -A POSTROUTING -o "$wwan_nic" -j MASQUERADE
    sudo iptables -t nat -A POSTROUTING -s "${net_base}.0/24" -j MASQUERADE
    sudo sysctl -w net.ipv4.ip_forward=1
    sudo systemctl restart isc-dhcp-server.service
    ;;
disable)
    sudo ip l s "$lan_nic" down
    sudo sysctl -w net.ipv4.ip_forward=0
    ;;
esac
