#!/bin/sh -ex

wwan_nic=${1:-wlp0s20f3}
lan_nic=${2:-enp0s31f6}
action=${3:-enable}
net_base=${4:-192.168.1}

sudo iptables --flush
sudo ip a f "$lan_nic"

case "$action" in
enable)

var=$(nmcli device show "$wwan_nic" | grep "DNS\[1\]" | grep -E  -o "([0-9]{1,3}\.){3}[0-9]{1,3}")
echo "DNS from wifi " $var

echo "ddns-update-style none;

authoritative;

subnet "${net_base}.0" netmask 255.255.255.0 {
  range "${net_base}.100" "${net_base}.180";
  option domain-name-servers ${var};
  option subnet-mask 255.255.255.0;
  option routers "${net_base}.1";
  option broadcast-address "${net_base}.255";
  default-lease-time 6000;
  max-lease-time 7200;
}" | sudo tee new_dhcp_conf.conf
    echo "config writed"
    sudo cp new_dhcp_conf.conf /etc/dhcp/dhcpd.conf


    sudo ip l s "$lan_nic" up
    sudo ip a a "${net_base}.1/24" dev "$lan_nic" brd + ||:
    sudo iptables -A FORWARD -o "$wwan_nic" -i "$lan_nic" -s "${net_base}.0/24" -m conntrack --ctstate NEW -j ACCEPT
    sudo iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    sudo iptables -t nat -F POSTROUTING

    sudo iptables -t nat -A POSTROUTING -o "$wwan_nic" -j MASQUERADE
    sudo iptables -t nat -A POSTROUTING -s "${net_base}.0/24" -j MASQUERADE
    sudo sysctl -w net.ipv4.ip_forward=1
    sudo systemctl restart isc-dhcp-server.service
    ;;
disable)
    sudo ip l s "$lan_nic" down
    sudo sysctl -w net.ipv4.ip_forward=0
    ;;
esac
