#!/bin/sh -ex

wwan_nic=${1:-wlp1s0}
lan_nic=${2:-enx4865ee1fcebb}
action=${3:-enable}
net_base=${4:-192.168.1}

sudo iptables --flush
sudo ip a f "$lan_nic"

case "$action" in
enable)

var=$(nmcli device show "$wwan_nic" | grep "DNS\[1\]" | grep -E  -o "([0-9]{1,3}\.){3}[0-9]{1,3}")
echo "DNS from wifi " $var

echo "ddns-update-style none;

authoritative;

subnet "${net_base}.0" netmask 255.255.255.0 {
  range "${net_base}.100" "${net_base}.180";
  option domain-name-servers ${var};
  option subnet-mask 255.255.255.0;
  option routers "${net_base}.1";
  option broadcast-address "${net_base}.255";
  default-lease-time 6000;
  max-lease-time 7200;
}" | sudo tee new_dhcp_conf.conf
echo "# Defaults for isc-dhcp-server (sourced by /etc/init.d/isc-dhcp-server)

# Path to dhcpd's config file (default: /etc/dhcp/dhcpd.conf).
#DHCPDv4_CONF=/etc/dhcp/dhcpd.conf
#DHCPDv6_CONF=/etc/dhcp/dhcpd6.conf

# Path to dhcpd's PID file (default: /var/run/dhcpd.pid).
#DHCPDv4_PID=/var/run/dhcpd.pid
#DHCPDv6_PID=/var/run/dhcpd6.pid

# Additional options to start dhcpd with.
#	Don't use options -cf or -pf here; use DHCPD_CONF/ DHCPD_PID instead
#OPTIONS=""

# On what interfaces should the DHCP server (dhcpd) serve DHCP requests?
#	Separate multiple interfaces with spaces, e.g. "eth0 eth1".
INTERFACESv4="${lan_nic}"
INTERFACESv6=\"\"
" | sudo tee new_isc-dhcp-server


    echo "config writed"
    sudo cp new_dhcp_conf.conf /etc/dhcp/dhcpd.conf
    sudo cp new_isc-dhcp-server /etc/default/isc-dhcp-server

    sudo ip l s "$lan_nic" up
    sudo ip a a "${net_base}.1/24" dev "$lan_nic" brd + ||:
    sudo iptables -A FORWARD -o "$wwan_nic" -i "$lan_nic" -s "${net_base}.0/24" -m conntrack --ctstate NEW -j ACCEPT
    sudo iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    sudo iptables -t nat -F POSTROUTING

    sudo iptables -t nat -A POSTROUTING -o "$wwan_nic" -j MASQUERADE
    sudo iptables -t nat -A POSTROUTING -s "${net_base}.0/24" -j MASQUERADE
    sudo sysctl -w net.ipv4.ip_forward=1
    sudo systemctl restart isc-dhcp-server.service
    ;;
disable)
    sudo ip l s "$lan_nic" down
    sudo sysctl -w net.ipv4.ip_forward=0
    ;;
esac
