#!/bin/sh -ex

lan_nic=${1:-enp0s31f6}
action=${2:-enable}
net_base=${3:-192.168.1}

#sudo iptables --flush
sudo ip a f "$lan_nic"

case "$action" in
enable)

echo "ddns-update-style none;

authoritative;

subnet "${net_base}.0" netmask 255.255.255.0 {
  range "${net_base}.100" "${net_base}.180";
  option domain-name-servers "${net_base}.1";
  option subnet-mask 255.255.255.0;
  option routers "${net_base}.1";
  option broadcast-address "${net_base}.255";
  default-lease-time 6000;
  max-lease-time 7200;
}" | sudo tee new_dhcp_conf.conf
    echo "config writed"
    sudo cp new_dhcp_conf.conf /etc/dhcp/dhcpd.conf


    sudo ip l s "$lan_nic" up
    sudo ip a a "${net_base}.1/24" dev "$lan_nic"
    sudo systemctl restart isc-dhcp-server.service
    ;;
disable)
    sudo ip l s "$lan_nic" down
#    sudo sysctl -w net.ipv4.ip_forward=0
    ;;
esac
