FROM ubuntu:24.04

ARG USERNAME=ubuntu

WORKDIR /workdir
RUN chmod -R 777 /workdir
RUN apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME 
# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME
RUN sudo apt install vim -y
